config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  resources :sessions, only: %i[new create destroy]
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :users
  
  resources :articles, only: %i[index new create show] do
    resources :votes, only: [:create, :destroy]
  end

  resources :categories, only: %i[show]
  root 'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_many :categories
  has_many :votes

  has_one_attached :image

  validates :title, presence: true
  validates :text, presence: true
  validates :image, presence: true

  validates_associated :categories

  accepts_nested_attributes_for :categories

  def main_thumbnail
    image.variant(resize: '1168x550!').processed
  end

  def secondary_thumbnail
    image.variant(resize: '900x400!').processed
  end

  def category_thumbnail
    image.variant(resize: '290x290!').processed
  end

  def thumbnail
    image.variant(resize: '292x272!').processed
  end

  def total_votes
    votes.count
  end

  def self.categories_one
    find_by_sql(['SELECT * FROM articles a JOIN categories c ON a.id = c.article_id
      WHERE c.priority = 1 ORDER BY a.created_at DESC LIMIT 1'])
  end

  def self.categories_two
    find_by_sql(['SELECT * FROM articles a JOIN categories c ON a.id = c.article_id
      WHERE c.priority = 2 ORDER BY a.created_at DESC LIMIT 1'])
  end

  def self.categories_three
    find_by_sql(['SELECT * FROM articles a JOIN categories c ON a.id = c.article_id
      WHERE c.priority = 3 ORDER BY a.created_at DESC LIMIT 1'])
  end

  def self.categories_four
    find_by_sql(['SELECT * FROM articles a JOIN categories c ON a.id = c.article_id
      WHERE c.priority = 4 ORDER BY a.created_at DESC LIMIT 1'])
  end

  def self.category_article(name)
    find_by_sql(['SELECT DISTINCT c.name, * FROM articles a JOIN categories c ON a.id = c.article_id WHERE c.name = ?', name])
  end

  def self.most_voted(article_id)
    find_by_sql(['SELECT * FROM articles WHERE id = ?', article_id])
  end

  def self.other_voted(article_id)
    find_by_sql(['SELECT * FROM articles WHERE id != ? ORDER BY created_at DESC', article_id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :user_authenticated, only: %i[index new create show]

  def index
    @main_articles = Article.most_voted(article_most_voted)
    @articles = Article.other_voted(article_most_voted)
    @one_articles = Article.categories_one
    @two_articles = Article.categories_two
    @three_articles = Article.categories_three
    @four_articles = Article.categories_four
  end

  def new
    @article = Article.new
    @article.categories.build
  end

  def create
    @article = current_user.articles.build(article_params)
    @article.image.attach(params[:article][:image])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :image, categories_attributes: %i[name priority])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  include ApplicationHelper

  def truncate(text, length = 30, truncate_string = '...')
    return if text.nil?

    l = length - truncate_string.chars.to_a.size
    (text.chars.to_a.size > length ? text.chars.to_a[0...l].join + truncate_string : text).to_s
  end
end

app/views/articles/_four_article.html.erb
<%= image_tag four_article.thumbnail %>
<div class='category-thumbnail-title ml-2 mr-2'>
  <%= link_to four_article.name, category_path(four_article.id) %>
</div>
<div class='category-thumbnail-text ml-2 mr-2 '>
  <p id='category-text' class='lead'><%= truncate(four_article.text, 50) %><p>
</div>

app/views/articles/_main_article.html.erb
<%= image_tag main_article.main_thumbnail %>
<div class='main-thumbnail-info'>
  <div class='main-thumbnail-title'>
    <%= link_to main_article.title, main_article %>
  </div>
  <div class='main-thumbnail-text'>
    <p id='article-text' class='lead'><%= truncate(main_article.text, 250) %><p>
  <div>
</div>

app/views/articles/_one_article.html.erb
<%= image_tag one_article.thumbnail %>
<div class='category-thumbnail-title ml-2 mr-2'>
  <%= link_to one_article.name, category_path(one_article.id) %>
</div>
<div class='category-thumbnail-text ml-2 mr-2 '>
  <p id='category-text' class='lead'><%= truncate(one_article.text, 50) %><p>
</div>

app/views/articles/_three_article.html.erb
<%= image_tag three_article.thumbnail %>
<div class='category-thumbnail-title ml-2 mr-2'>
  <%= link_to three_article.name, category_path(three_article.id) %>
</div>
<div class='category-thumbnail-text ml-2 mr-2 '>
  <p id='category-text' class='lead'><%= truncate(three_article.text, 50) %><p>
</div>

app/views/articles/_two_article.html.erb
<%= image_tag two_article.thumbnail %>
<div class='category-thumbnail-title ml-2 mr-2'>
  <%= link_to two_article.name, category_path(two_article.id) %>
</div>
<div class='category-thumbnail-text ml-2 mr-2 '>
  <p id='category-text' class='lead'><%= truncate(two_article.text, 50) %><p>
</div>

app/views/articles/index.html.erb
<div id='main-index'>
  <div id='main-id' class='row'>
    <%= render partial: 'main_article', collection: @main_articles %>
  </div>
  <div id='secondary-id' class='row'>
    <div class="category-img">
      <%= render partial: 'one_article', collection: @one_articles %>
    </div>
    <% if @two_articles.count > 0 %>
      <div class="category-img">
        <%= render partial: 'two_article', collection: @two_articles %>
      </div>
    <% end %>
    <% if @three_articles.count > 0 %>
      <div class="category-img">
        <%= render partial: 'three_article', collection: @three_articles %>
      </div>
    <% end %>
    <% if @four_articles.count > 0 %>
      <div class="category-img">
        <%= render partial: 'four_article', collection: @four_articles %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
  <h3 class="text-center topic">Register</h3>
  <div id='article-div' class="d-flex justify-content-center">
    <%= form_with(model: @article, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :title, class: 'col col-form-label' %>
        <div class="col">
          <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :text, class: 'col col-form-label' %>
        <div class="col">
          <%= f.text_area :text, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :image, class: 'col col-form-label' %>
        <div class="col">
          <%= f.file_field :image, class: 'form-control' %>
        </div>
      </div>
      <%= f.fields_for :categories do |ff| %>
        <div class="form-group">
          <%= ff.label :name, class: 'col col-form-label' %>
          <div class="col">
            <%= ff.select(:name, ['Tech', 'Business', 'Food', 'Wildlife'], {}, { class: 'form-control' }) %>
          </div>
        </div>
      <% end %>
      <div class="form-row text-center mb-3 pb-3">
        <div class="col-12">
          <%= f.submit 'Save', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>

app/views/articles/show.html.erb
<div class='d-flex justify-content-center mt-2'>
  <%= image_tag @article.secondary_thumbnail %>
</div>
<div class='mt-3'>
  <div class='show-container'>
    <%= @article.text %>
  </div>
</div>
<div id='form-vote' class="d-flex justify-content-center form-row text-center mt-2">
  <div id="vote-div" class="col-3">
    <%= form_tag article_votes_path(@article.id), method: :post do %>
      <%= hidden_field_tag :article_id, current_user.id %>
      <%= submit_tag "Vote", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>
<div class='d-flex justify-content-center mt-2 mb-3'>
  <br><%= @article.total_votes %> votes
</div>